version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount ein Init-Skript, um die Datenbank beim ersten Start zu konfigurieren
      # - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
