namespace Leoweb.Server.Database.Models
{
    public enum Subject
    {
        D,
        E,
        AM,
        POSE,
        LOAL,
        SYP,
        WMC,
        DBI,
        BO,
        RW,
        NWC,
        BSPM,
        DSAI,
        GGPGW,
        GGPGP,
        NSCS,
        NWP,
        NWCH,
        RK,
        RI,
        ETH,
        CABS,
        SEW,
        ITP,
        VERT,
        NWT,
        ITSI,
        CPR,
        SD,
        UIUX,
        MEDPR,
        SYTSW,
        SYTEL,
        INSY,
        MEDTPD,
        MEDTSM,
        HE,
        HED,
        GME,
        FST,
        MTRS,
        SOPK,
        PBEU,
        WRWI,
        LA,
        DIC,
        ROR,
        KSN,
        EPMEL,
        MINF,
        BSV,
        MGT,
        PMW,
        BSVU,
        LAU,
        CNTNT,
        AUTO,
        UNF,
        AE,
        WEPT,
        ELD,
        KME,
        MAM,
        SPK,
        SOTE,
        BSVB,
        BSVE,
        BMG,
        RFKR,
        EBA_BMG
    }

    public static class Branch
    {
		public static List<Subject> Informatik {
            get
            {
                return new List<Subject>()
                { 
                    Subject.AM,
                    Subject.RK,
                    Subject.ETH,
                    Subject.D,
                    Subject.E,
                    Subject.GGPGP,
                    Subject.GGPGW,
                    Subject.BSPM,
                    Subject.NWC,
                    Subject.NWP,
                    Subject.SOPK,
                    Subject.CABS,
                    Subject.POSE,
                    Subject.DBI,
                    Subject.NSCS,
                    Subject.WMC,
                    Subject.DSAI,
                    Subject.BO,
                    Subject.RW,
                    Subject.SYP
                };
            }
        }
		public static List<Subject> Medientechnik
		{
			get
			{
				return new List<Subject>()
				{
					Subject.AM,
					Subject.RK,
					Subject.ETH,
					Subject.D,
					Subject.E,
					Subject.GGPGP,
					Subject.GGPGW,
					Subject.BSPM,
					Subject.NWC,
					Subject.NWP,
					Subject.SOPK,
					Subject.SEW,
					Subject.ITP,
					Subject.INSY,
					Subject.SYTSW,
					Subject.MEDTPD,
					Subject.MEDTSM,
					Subject.NSCS,
					Subject.ITSI,
					Subject.CPR,
					Subject.MEDPR
				};
			}
		}
		public static List<Subject> Elektronik
		{
			get
			{
				return new List<Subject>()
				{
					Subject.AM,
					Subject.RK,
					Subject.ETH,
					Subject.D,
					Subject.E,
					Subject.GGPGP,
					Subject.GGPGW,
					Subject.BSPM,
					Subject.NWC,
					Subject.NWP,
					Subject.SOPK,
					Subject.HE,
					Subject.MEDTSM,
					Subject.DIC,
					Subject.KSN,
					Subject.FST,
					Subject.LA,
					Subject.PBEU,
					Subject.EPMEL
				};
			}
		}
		public static List<Subject> Medizintechnik
		{
			get
			{
				return new List<Subject>()
				{
					Subject.AM,
					Subject.RK,
					Subject.ETH,
					Subject.D,
					Subject.E,
					Subject.GGPGP,
					Subject.GGPGW,
					Subject.BSPM,
					Subject.NWC,
					Subject.NWP,
					Subject.SOPK,
					Subject.BMG,
					Subject.BSV,
					Subject.MGT,
					Subject.GME,
					Subject.LA,
					Subject.EPMEL,
					Subject.PBEU
				};
			}
		}
	}
}
