apiVersion: apps/v1
kind: Deployment
metadata:
  name: leoweb-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leoweb-backend
  template:
    metadata:
      labels:
        app: leoweb-backend
    spec:
      containers:
      - name: leoweb-backend
        image: leoweb-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        envFrom:
        - configMapRef:
            name: leoweb-config
---
apiVersion: v1
kind: Service
metadata:
  name: leoweb-backend
spec:
  selector:
    app: leoweb-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP