apiVersion: apps/v1
kind: Deployment
metadata:
  name: leoweb-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leoweb-client
  template:
    metadata:
      labels:
        app: leoweb-client
    spec:
      containers:
      - name: leoweb-client
        image: leoweb-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: leoweb-client
spec:
  selector:
    app: leoweb-client
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leoweb-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: leoweb-client
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: leoweb-backend
            port:
              number: 5000