name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: Leoweb/leoweb.client

      - name: Build the Angular app
        run: npm run build -- --output-path=dist --base-href="/"
        working-directory: Leoweb/leoweb.client

      - name: List dist directory contents
        run: ls -la Leoweb/leoweb.client/dist

      - name: Check if the build directory exists
        run: |
          if [ ! -d "Leoweb/leoweb.client/dist/browser" ]; then
            echo "Build failed: Browser directory does not exist!"
            exit 1
          else
            echo "Build succeeded: Browser directory found!"
          fi

      - name: Build And Deploy to Azure
        if: success()  # Ensure this step only runs if the previous steps succeeded
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_BAY_0F0554A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "Leoweb/leoweb.client" # Path to your frontend code
          api_location: "" # Optional, leave empty if you don't have an API
          output_location: "dist/leoweb.client/browser" # Correct output path for your setup

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "./Leoweb/leoweb.client"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_BAY_0F0554A03 }}
          action: "close"
