name: Build Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Angular Project

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: Leoweb/leoweb.client

      - name: Build the Angular app
        run: npm run build -- --output-path=dist --base-href="/"
        working-directory: Leoweb/leoweb.client

      - name: List dist directory contents
        run: ls -la Leoweb/leoweb.client/dist

      - name: Check if the build directory exists
        run: |
          if [ ! -d "Leoweb/leoweb.client/dist/browser" ]; then
            echo "Build failed: Browser directory does not exist!"
            exit 1
          else
            echo "Build succeeded: Browser directory found!"
          fi
